// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcBach.Data;

#nullable disable

namespace MvcBach.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240412071157_Cre_Table_HS")]
    partial class Cre_Table_HS
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("MvcBach.Models.Hocsinh", b =>
                {
                    b.Property<string>("HocsinhID")
                        .HasColumnType("TEXT");

                    b.HasKey("HocsinhID");

                    b.ToTable("HS");
                });

            modelBuilder.Entity("MvcBach.Models.Person", b =>
                {
                    b.Property<string>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PersonId");

                    b.ToTable("Persons");
                });
#pragma warning restore 612, 618
        }
    }
}
